import { motion, AnimatePresence } from 'framer-motion';
import { X } from 'lucide-react';
import { PieChart, Pie, Cell, Tooltip, ResponsiveContainer } from 'recharts';
import { useData } from '@/contexts/DataContext';
import { useMemo } from 'react';
import { getGroupCategory } from '@/lib/dataProcessor';
import { formatMoney, formatPercent } from './DataTable';

interface OfficerModalProps {
  isOpen: boolean;
  onClose: () => void;
  officerName: string;
}

const CATEGORIES = [
  { key: 'Mac', color: '#10b981' },
  { key: 'iPad', color: '#ef4444' },
  { key: 'iPhone', color: '#3b82f6' },
  { key: 'Apple Watch', color: '#8b5cf6' },
  { key: 'BTB(Apple)', color: '#6366f1' },
  { key: 'BTB', color: '#f59e0b' },
  { key: 'Cover+', color: '#ec4899' },
  { key: 'Apple Care', color: '#14b8a6' },
  { key: 'Other', color: '#6b7280' },
];

export default function OfficerModal({ isOpen, onClose, officerName }: OfficerModalProps) {
  const data = useData();

  const salesMix = useMemo(() => {
    if (!officerName || !data.isLoaded.currentPeriod || !data.isLoaded.targets) return [];

    // Find targets for this officer
    const tName = officerName.trim().toLowerCase();
    
    // We try to match TargetRow just like we do in dataProcessor
    const targetRow = data.targets.find(t => {
      const tn = t.name.trim().toLowerCase();
      const fn = `${t.name.trim()} ${t.surname.trim()}`.toLowerCase();
      // Since officerName here comes directly from the DataTable which was generated BY officerSummary, 
      // officerName is actually exactly targetRow.name ! Look at calculateOfficerSummary: `officerName: t.name`
      return tn === tName || fn === tName;
    }) || { 
      mac: 0, ipad: 0, iphone: 0, appleWatch: 0, btbApple: 0, btb: 0 
    } as any;

    // Filter current sales for this officer using the same robust logic
    const officerSales = data.currentPeriod.filter(s => {
      if (targetRow.staffId && s.officerId && targetRow.staffId === s.officerId) return true;
      const sn = (s.officerName || '').trim().toLowerCase();
      return sn === tName || sn.startsWith(tName + ' ');
    });

    const results: Record<string, { target: number, actual: number, color: string }> = {};
    CATEGORIES.forEach(c => {
      let t = 0;
      if (c.key === 'Mac') t = targetRow.mac || 0;
      if (c.key === 'iPad') t = targetRow.ipad || 0;
      if (c.key === 'iPhone') t = targetRow.iphone || 0;
      if (c.key === 'Apple Watch') t = targetRow.appleWatch || 0;
      if (c.key === 'BTB(Apple)') t = targetRow.btbApple || 0;
      if (c.key === 'BTB') t = targetRow.btb || 0;

      results[c.key] = { target: t, actual: 0, color: c.color };
    });

    officerSales.forEach(s => {
      const gc = getGroupCategory(s.categoryName || '', s.subCategory || '', data.categoryMaster);
      let mapKey = 'Other';
      if (gc === 'Mac') mapKey = 'Mac';
      else if (gc === 'iPad') mapKey = 'iPad';
      else if (gc === 'iPhone') mapKey = 'iPhone';
      else if (gc === 'Apple Watch') mapKey = 'Apple Watch';
      else if (gc === 'BTB(Apple)') mapKey = 'BTB(Apple)';
      else if (gc === 'BTB') mapKey = 'BTB';
      else if (gc === 'Apple Care') mapKey = 'Apple Care';
      
      // Heuristic for Cover+ since it might not be in group category map directly
      else if ((s.productName || '').toUpperCase().includes('COVER+')) mapKey = 'Cover+';
      else if (CATEGORIES.some(c => c.key === gc)) mapKey = gc;

      if (results[mapKey]) {
        results[mapKey].actual += s.totalPrice || 0;
      }
    });

    return Object.keys(results).map(key => ({
      name: key,
      target: results[key].target,
      actual: results[key].actual,
      color: results[key].color,
      achPercent: results[key].target > 0 ? (results[key].actual / results[key].target) * 100 : 0
    }));

  }, [officerName, data]);

  const pieData = salesMix.filter(s => s.actual > 0);

  if (!isOpen) return null;

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-[100] flex items-center justify-center bg-[#0a1128]/60 backdrop-blur-md p-4 md:p-8">
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 30 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 30 }}
          transition={{ type: 'spring', damping: 25, stiffness: 300 }}
          className="bg-white rounded-[24px] shadow-2xl w-full max-w-5xl overflow-hidden max-h-full flex flex-col relative"
        >
          {/* Header */}
          <div className="px-8 py-7 border-b border-gray-100 flex items-center justify-between bg-white relative z-10">
            <div>
              <h2 className="text-3xl font-black text-gray-900 tracking-tight">{officerName}</h2>
              <p className="text-[11px] font-bold text-blue-600 uppercase tracking-widest mt-1">Individual Sales Mix Breakdown</p>
            </div>
            <button 
              onClick={onClose}
              className="p-2.5 bg-gray-50 text-gray-400 hover:text-gray-700 hover:bg-gray-100 rounded-full transition-all duration-200"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          <div className="flex flex-col lg:flex-row p-8 gap-12 overflow-y-auto bg-[#fafafa]">
            {/* Left: Pie Chart */}
            <div className="w-full lg:w-5/12 flex flex-col items-center pt-4">
              <h3 className="text-xs font-bold text-gray-400 tracking-widest uppercase mb-6">Actual Sales Mix</h3>
              {pieData.length > 0 ? (
                <div className="w-full h-[320px] relative flex items-center justify-center">
                  <ResponsiveContainer width="100%" height="100%">
                    <PieChart>
                      <Pie
                        data={pieData}
                        cx="50%"
                        cy="50%"
                        innerRadius={80}
                        outerRadius={120}
                        paddingAngle={3}
                        dataKey="actual"
                        stroke="none"
                        cornerRadius={4}
                      >
                        {pieData.map((entry, index) => (
                          <Cell key={`cell-${index}`} fill={entry.color} />
                        ))}
                      </Pie>
                      <Tooltip 
                        formatter={(value: number) => ['฿' + value.toLocaleString(), 'Revenue']}
                        contentStyle={{ borderRadius: '12px', border: '1px solid #f3f4f6', boxShadow: '0 8px 24px rgba(0,0,0,0.12)', fontWeight: 'bold' }}
                        itemStyle={{ color: '#1f2937' }}
                      />
                    </PieChart>
                  </ResponsiveContainer>
                  <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                    <div className="text-center">
                      <p className="text-3xl font-black text-gray-800">
                        {(pieData.reduce((sum, item) => sum + item.actual, 0) / 1000000).toFixed(2)}M
                      </p>
                      <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Total</p>
                    </div>
                  </div>
                </div>
              ) : (
                <div className="text-gray-400 flex items-center justify-center h-[320px] text-sm italic bg-white w-full rounded-2xl border border-gray-100 shadow-sm">
                  No sales payload available
                </div>
              )}
            </div>

            {/* Right: Table */}
            <div className="w-full lg:w-7/12 bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b-2 border-gray-100 text-gray-400 text-[10px] uppercase tracking-widest">
                    <th className="text-left font-bold pb-4 pr-3">Category</th>
                    <th className="text-right font-bold pb-4 px-3 w-1/4">Target</th>
                    <th className="text-right font-bold pb-4 px-3 w-1/4">Actual</th>
                    <th className="text-right font-bold pb-4 pl-3 w-[80px]">% Ach.</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-50">
                  {salesMix.map((row) => (
                    <tr key={row.name} className="hover:bg-[#f8fafc] transition-colors group">
                      <td className="py-3.5 pr-3 font-bold text-gray-800 text-xs flex items-center gap-2.5">
                        <span className="w-2.5 h-2.5 rounded-full inline-block shadow-sm" style={{ backgroundColor: row.color }} />
                        {row.name}
                      </td>
                      <td className="py-3.5 px-3 text-right text-gray-400 tabular-nums text-xs font-medium">
                        {row.target > 0 ? formatMoney(row.target) : '-'}
                      </td>
                      <td className="py-3.5 px-3 text-right tabular-nums text-xs">
                        <span className="text-blue-600 font-bold">
                          {row.actual > 0 ? formatMoney(row.actual) : '0'} 
                        </span>
                        <span className="text-[9px] text-gray-400 font-normal ml-1">฿</span>
                      </td>
                      <td className="py-3.5 pl-3 text-right tabular-nums text-xs">
                        {row.target > 0 ? (
                           <div className={`inline-flex items-center justify-center px-2 py-1 rounded-md ${row.achPercent >= 100 ? "bg-emerald-50 text-emerald-600" : row.achPercent >= 80 ? "bg-amber-50 text-amber-600" : "bg-rose-50 text-rose-600"} font-bold`}>
                             {formatPercent(row.achPercent)}
                           </div>
                        ) : (
                          <span className="text-gray-300">-</span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}
