import { motion, AnimatePresence } from 'framer-motion';
import { X } from 'lucide-react';
import { PieChart, Pie, Cell, Tooltip, ResponsiveContainer } from 'recharts';
import { useData } from '@/contexts/DataContext';
import { useMemo } from 'react';
import { getGroupCategory } from '@/lib/dataProcessor';
import { formatMoney, formatPercent } from './DataTable';

interface OfficerModalProps {
  isOpen: boolean;
  onClose: () => void;
  officerName: string;
}

const CATEGORIES = [
  { key: 'Mac', color: '#10b981' },
  { key: 'iPad', color: '#ef4444' },
  { key: 'iPhone', color: '#3b82f6' },
  { key: 'Apple Watch', color: '#8b5cf6' },
  { key: 'BTB(Apple)', color: '#6366f1' },
  { key: 'BTB', color: '#f59e0b' },
  { key: 'Cover+', color: '#ec4899' },
  { key: 'Apple Care', color: '#14b8a6' },
  { key: 'Other', color: '#6b7280' },
];

export default function OfficerModal({ isOpen, onClose, officerName }: OfficerModalProps) {
  const data = useData();

  const salesMix = useMemo(() => {
    if (!officerName || !data.isLoaded.currentPeriod || !data.isLoaded.targets) return [];

    // Find targets for this officer
    const tName = officerName.trim().toLowerCase();
    
    // We try to match TargetRow just like we do in dataProcessor
    const targetRow = data.targets.find(t => {
      const tn = t.name.trim().toLowerCase();
      const fn = `${t.name.trim()} ${t.surname.trim()}`.toLowerCase();
      // Since officerName here comes directly from the DataTable which was generated BY officerSummary, 
      // officerName is actually exactly targetRow.name ! Look at calculateOfficerSummary: `officerName: t.name`
      return tn === tName || fn === tName;
    }) || { 
      mac: 0, ipad: 0, iphone: 0, appleWatch: 0, btbApple: 0, btb: 0 
    } as any;

    // Filter current sales for this officer using the same robust logic
    const officerSales = data.currentPeriod.filter(s => {
      if (targetRow.staffId && s.officerId && targetRow.staffId === s.officerId) return true;
      const sn = (s.officerName || '').trim().toLowerCase();
      return sn === tName || sn.startsWith(tName + ' ');
    });

    const results: Record<string, { target: number, actual: number, color: string }> = {};
    CATEGORIES.forEach(c => {
      let t = 0;
      if (c.key === 'Mac') t = targetRow.mac || 0;
      if (c.key === 'iPad') t = targetRow.ipad || 0;
      if (c.key === 'iPhone') t = targetRow.iphone || 0;
      if (c.key === 'Apple Watch') t = targetRow.appleWatch || 0;
      if (c.key === 'BTB(Apple)') t = targetRow.btbApple || 0;
      if (c.key === 'BTB') t = targetRow.btb || 0;

      results[c.key] = { target: t, actual: 0, color: c.color };
    });

    officerSales.forEach(s => {
      const gc = getGroupCategory(s.categoryName || '', s.subCategory || '', data.categoryMaster);
      let mapKey = 'Other';
      if (gc === 'Mac') mapKey = 'Mac';
      else if (gc === 'iPad') mapKey = 'iPad';
      else if (gc === 'iPhone') mapKey = 'iPhone';
      else if (gc === 'Apple Watch') mapKey = 'Apple Watch';
      else if (gc === 'BTB(Apple)') mapKey = 'BTB(Apple)';
      else if (gc === 'BTB') mapKey = 'BTB';
      else if (gc === 'Apple Care') mapKey = 'Apple Care';
      
      // Heuristic for Cover+ since it might not be in group category map directly
      else if ((s.productName || '').toUpperCase().includes('COVER+')) mapKey = 'Cover+';
      else if (CATEGORIES.some(c => c.key === gc)) mapKey = gc;

      if (results[mapKey]) {
        results[mapKey].actual += s.totalPrice || 0;
      }
    });

    return Object.keys(results).map(key => ({
      name: key,
      target: results[key].target,
      actual: results[key].actual,
      color: results[key].color,
      achPercent: results[key].target > 0 ? (results[key].actual / results[key].target) * 100 : 0
    }));

  }, [officerName, data]);

  const pieData = salesMix.filter(s => s.actual > 0);

  if (!isOpen) return null;

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4">
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 20 }}
          className="bg-white rounded-2xl shadow-2xl w-full max-w-4xl overflow-hidden max-h-[90vh] flex flex-col"
        >
          {/* Header */}
          <div className="flex items-center justify-between p-6 border-b border-gray-100">
            <div>
              <h2 className="text-2xl font-black text-gray-900 tracking-tight">{officerName}</h2>
              <p className="text-[10px] font-bold text-blue-600 uppercase tracking-widest mt-1">Individual Sales Mix Breakdown</p>
            </div>
            <button 
              onClick={onClose}
              className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-full transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          <div className="flex flex-col md:flex-row p-6 gap-8 overflow-y-auto">
            {/* Left: Pie Chart */}
            <div className="w-full md:w-1/2 flex flex-col items-center justify-center min-h-[300px]">
              <h3 className="text-xs font-bold text-gray-400 tracking-widest uppercase mb-4">Actual Sales Mix</h3>
              {pieData.length > 0 ? (
                <ResponsiveContainer width="100%" height={250}>
                  <PieChart>
                    <Pie
                      data={pieData}
                      cx="50%"
                      cy="50%"
                      innerRadius={60}
                      outerRadius={100}
                      paddingAngle={2}
                      dataKey="actual"
                      stroke="none"
                    >
                      {pieData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.color} />
                      ))}
                    </Pie>
                    <Tooltip 
                      formatter={(value: number) => ['฿' + value.toLocaleString(), 'Actual Sales']}
                      contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 12px rgba(0,0,0,0.1)' }}
                    />
                  </PieChart>
                </ResponsiveContainer>
              ) : (
                <div className="text-gray-400 text-sm italic">No sales data available</div>
              )}
            </div>

            {/* Right: Table */}
            <div className="w-full md:w-1/2">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b-2 border-gray-100 text-gray-400 text-[10px] uppercase tracking-widest">
                    <th className="text-left font-bold py-3 pr-2">Category</th>
                    <th className="text-right font-bold py-3 px-2">Target</th>
                    <th className="text-right font-bold py-3 px-2">Actual</th>
                    <th className="text-right font-bold py-3 pl-2">% Ach.</th>
                  </tr>
                </thead>
                <tbody>
                  {salesMix.map((row) => (
                    <tr key={row.name} className="border-b border-gray-50 hover:bg-gray-50/50 transition-colors">
                      <td className="py-3 pr-2 font-bold text-gray-700 text-xs">
                        {row.name}
                      </td>
                      <td className="py-3 px-2 text-right text-gray-500 tabular-nums text-xs">
                        {row.target > 0 ? formatMoney(row.target) : '-'}
                      </td>
                      <td className="py-3 px-2 text-right text-blue-600 font-bold tabular-nums text-xs">
                        {row.actual > 0 ? formatMoney(row.actual) : '0'} 
                        <span className="text-[9px] text-gray-400 font-normal ml-1">฿</span>
                      </td>
                      <td className="py-3 pl-2 text-right tabular-nums text-xs">
                        {row.target > 0 ? (
                           <span className={row.achPercent >= 100 ? "text-emerald-500 font-bold" : "text-rose-500 font-bold"}>
                             {formatPercent(row.achPercent)}
                           </span>
                        ) : (
                          <span className="text-gray-300">-</span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}
